// Generated by gencpp from file unity_meta_quest_msgs/PositionServiceRequest.msg
// DO NOT EDIT!


#ifndef UNITY_META_QUEST_MSGS_MESSAGE_POSITIONSERVICEREQUEST_H
#define UNITY_META_QUEST_MSGS_MESSAGE_POSITIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <unity_meta_quest_msgs/PosRot.h>

namespace unity_meta_quest_msgs
{
template <class ContainerAllocator>
struct PositionServiceRequest_
{
  typedef PositionServiceRequest_<ContainerAllocator> Type;

  PositionServiceRequest_()
    : input()  {
    }
  PositionServiceRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::unity_meta_quest_msgs::PosRot_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionServiceRequest_

typedef ::unity_meta_quest_msgs::PositionServiceRequest_<std::allocator<void> > PositionServiceRequest;

typedef boost::shared_ptr< ::unity_meta_quest_msgs::PositionServiceRequest > PositionServiceRequestPtr;
typedef boost::shared_ptr< ::unity_meta_quest_msgs::PositionServiceRequest const> PositionServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator1> & lhs, const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator1> & lhs, const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_meta_quest_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e1dd27b40d577e01a5f9128d82cf0d0";
  }

  static const char* value(const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e1dd27b40d577e0ULL;
  static const uint64_t static_value2 = 0x1a5f9128d82cf0d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_meta_quest_msgs/PositionServiceRequest";
  }

  static const char* value(const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PosRot input\n"
"\n"
"================================================================================\n"
"MSG: unity_meta_quest_msgs/PosRot\n"
"float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
"float32 rot_x\n"
"float32 rot_y\n"
"float32 rot_z\n"
"float32 rot_w\n"
"string name\n"
;
  }

  static const char* value(const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_meta_quest_msgs::PositionServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_META_QUEST_MSGS_MESSAGE_POSITIONSERVICEREQUEST_H
