// Generated by gencpp from file unity_meta_quest_msgs/PositionService.msg
// DO NOT EDIT!


#ifndef UNITY_META_QUEST_MSGS_MESSAGE_POSITIONSERVICE_H
#define UNITY_META_QUEST_MSGS_MESSAGE_POSITIONSERVICE_H

#include <ros/service_traits.h>


#include <unity_meta_quest_msgs/PositionServiceRequest.h>
#include <unity_meta_quest_msgs/PositionServiceResponse.h>


namespace unity_meta_quest_msgs
{

struct PositionService
{

typedef PositionServiceRequest Request;
typedef PositionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionService
} // namespace unity_meta_quest_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unity_meta_quest_msgs::PositionService > {
  static const char* value()
  {
    return "74d162dfa312ad5f1087485ee56d06ee";
  }

  static const char* value(const ::unity_meta_quest_msgs::PositionService&) { return value(); }
};

template<>
struct DataType< ::unity_meta_quest_msgs::PositionService > {
  static const char* value()
  {
    return "unity_meta_quest_msgs/PositionService";
  }

  static const char* value(const ::unity_meta_quest_msgs::PositionService&) { return value(); }
};


// service_traits::MD5Sum< ::unity_meta_quest_msgs::PositionServiceRequest> should match
// service_traits::MD5Sum< ::unity_meta_quest_msgs::PositionService >
template<>
struct MD5Sum< ::unity_meta_quest_msgs::PositionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unity_meta_quest_msgs::PositionService >::value();
  }
  static const char* value(const ::unity_meta_quest_msgs::PositionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_meta_quest_msgs::PositionServiceRequest> should match
// service_traits::DataType< ::unity_meta_quest_msgs::PositionService >
template<>
struct DataType< ::unity_meta_quest_msgs::PositionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::unity_meta_quest_msgs::PositionService >::value();
  }
  static const char* value(const ::unity_meta_quest_msgs::PositionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unity_meta_quest_msgs::PositionServiceResponse> should match
// service_traits::MD5Sum< ::unity_meta_quest_msgs::PositionService >
template<>
struct MD5Sum< ::unity_meta_quest_msgs::PositionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unity_meta_quest_msgs::PositionService >::value();
  }
  static const char* value(const ::unity_meta_quest_msgs::PositionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_meta_quest_msgs::PositionServiceResponse> should match
// service_traits::DataType< ::unity_meta_quest_msgs::PositionService >
template<>
struct DataType< ::unity_meta_quest_msgs::PositionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::unity_meta_quest_msgs::PositionService >::value();
  }
  static const char* value(const ::unity_meta_quest_msgs::PositionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNITY_META_QUEST_MSGS_MESSAGE_POSITIONSERVICE_H
