// Generated by gencpp from file unity_meta_quest_msgs/PosRot.msg
// DO NOT EDIT!


#ifndef UNITY_META_QUEST_MSGS_MESSAGE_POSROT_H
#define UNITY_META_QUEST_MSGS_MESSAGE_POSROT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unity_meta_quest_msgs
{
template <class ContainerAllocator>
struct PosRot_
{
  typedef PosRot_<ContainerAllocator> Type;

  PosRot_()
    : pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , rot_w(0.0)
    , name()  {
    }
  PosRot_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , rot_w(0.0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _pos_z_type;
  _pos_z_type pos_z;

   typedef float _rot_x_type;
  _rot_x_type rot_x;

   typedef float _rot_y_type;
  _rot_y_type rot_y;

   typedef float _rot_z_type;
  _rot_z_type rot_z;

   typedef float _rot_w_type;
  _rot_w_type rot_w;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> const> ConstPtr;

}; // struct PosRot_

typedef ::unity_meta_quest_msgs::PosRot_<std::allocator<void> > PosRot;

typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRot > PosRotPtr;
typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRot const> PosRotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator1> & lhs, const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator2> & rhs)
{
  return lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.pos_z == rhs.pos_z &&
    lhs.rot_x == rhs.rot_x &&
    lhs.rot_y == rhs.rot_y &&
    lhs.rot_z == rhs.rot_z &&
    lhs.rot_w == rhs.rot_w &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator1> & lhs, const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_meta_quest_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0e396f41a876de177e09f3c627fd741";
  }

  static const char* value(const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0e396f41a876de1ULL;
  static const uint64_t static_value2 = 0x77e09f3c627fd741ULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_meta_quest_msgs/PosRot";
  }

  static const char* value(const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
"float32 rot_x\n"
"float32 rot_y\n"
"float32 rot_z\n"
"float32 rot_w\n"
"string name\n"
;
  }

  static const char* value(const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
      stream.next(m.rot_w);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosRot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_meta_quest_msgs::PosRot_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<float>::stream(s, indent + "  ", v.pos_z);
    s << indent << "rot_x: ";
    Printer<float>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<float>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<float>::stream(s, indent + "  ", v.rot_z);
    s << indent << "rot_w: ";
    Printer<float>::stream(s, indent + "  ", v.rot_w);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_META_QUEST_MSGS_MESSAGE_POSROT_H
