// Generated by gencpp from file unity_meta_quest_msgs/PosRotList.msg
// DO NOT EDIT!


#ifndef UNITY_META_QUEST_MSGS_MESSAGE_POSROTLIST_H
#define UNITY_META_QUEST_MSGS_MESSAGE_POSROTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <unity_meta_quest_msgs/PosRot.h>

namespace unity_meta_quest_msgs
{
template <class ContainerAllocator>
struct PosRotList_
{
  typedef PosRotList_<ContainerAllocator> Type;

  PosRotList_()
    : devices()  {
    }
  PosRotList_(const ContainerAllocator& _alloc)
    : devices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >> _devices_type;
  _devices_type devices;





  typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> const> ConstPtr;

}; // struct PosRotList_

typedef ::unity_meta_quest_msgs::PosRotList_<std::allocator<void> > PosRotList;

typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRotList > PosRotListPtr;
typedef boost::shared_ptr< ::unity_meta_quest_msgs::PosRotList const> PosRotListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator1> & lhs, const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator2> & rhs)
{
  return lhs.devices == rhs.devices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator1> & lhs, const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_meta_quest_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "439e0451c819cb409f987681338dd04c";
  }

  static const char* value(const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x439e0451c819cb40ULL;
  static const uint64_t static_value2 = 0x9f987681338dd04cULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_meta_quest_msgs/PosRotList";
  }

  static const char* value(const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PosRot[] devices\n"
"================================================================================\n"
"MSG: unity_meta_quest_msgs/PosRot\n"
"float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
"float32 rot_x\n"
"float32 rot_y\n"
"float32 rot_z\n"
"float32 rot_w\n"
"string name\n"
;
  }

  static const char* value(const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.devices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosRotList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_meta_quest_msgs::PosRotList_<ContainerAllocator>& v)
  {
    s << indent << "devices[]" << std::endl;
    for (size_t i = 0; i < v.devices.size(); ++i)
    {
      s << indent << "  devices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::unity_meta_quest_msgs::PosRot_<ContainerAllocator> >::stream(s, indent + "    ", v.devices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_META_QUEST_MSGS_MESSAGE_POSROTLIST_H
