//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMetaQuest
{
    [Serializable]
    public class PosRotListMsg : Message
    {
        public const string k_RosMessageName = "unity_meta_quest_msgs/PosRotList";
        public override string RosMessageName => k_RosMessageName;

        public PosRotMsg[] devices;

        public PosRotListMsg()
        {
            this.devices = new PosRotMsg[0];
        }

        public PosRotListMsg(PosRotMsg[] devices)
        {
            this.devices = devices;
        }

        public static PosRotListMsg Deserialize(MessageDeserializer deserializer) => new PosRotListMsg(deserializer);

        private PosRotListMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.devices, PosRotMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.devices);
            serializer.Write(this.devices);
        }

        public override string ToString()
        {
            return "PosRotListMsg: " +
            "\ndevices: " + System.String.Join(", ", devices.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
